version: '3'

services:

  # Postgres Database
  ud-postgres:
    image: "ud-postgres" # use latest official postgres version
    container_name: ud-postgres
    env_file:
      - ./postgres/database.env # configure postgres
    build:
      context: ./postgres
    ports:
      - "54321:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/ud-postgresql/data/ # persist data even if container shuts down

  # Mongo Database
  ud-mongodb:
    image: "mongo"
    volumes:
      - ./mongodb:/var/mongo/data
    ports:
      - "27017:27017"

  # API Gateway
  # Proxies requests to internal service
  ud-gateway:
    image: ud-gateway
    container_name: ud-gateway
    depends_on: 
      - ud-gatekeeper-ms
      - ud-gatekeeper
      - ud-mongodb
    build:
      context: ./gateway
    volumes: 
      - ./gateway:/var/log/nginx/
    ports: 
      - "80:80"

  # RabbitMQ for microservice communication
  ud-rabbitmq:
    image: rabbitmq:3-management
    container_name: ud-rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"

  # GateKeeper microservice 
  ud-gatekeeper-ms:
    image: gatekeeper-ms
    container_name: ud-gatekeeper-ms
    depends_on:
      - ud-rabbitmq
      - ud-mongodb
    build:
      context: ./gatekeeper-ms
      target: debug
    volumes:
      - ./gatekeeper-ms:/app
      - /app/node_modules
    restart: on-failure

  # GateKeeper API 
  ud-gatekeeper:
    image: ud-gatekeeper
    container_name: ud-gatekeeper
    depends_on:
      - ud-rabbitmq
    build:
      context: ./gatekeeper
      target: debug
    volumes:
      - ./gatekeeper:/app
      - /app/node_modules
    ports: 
      - "3000:3000"
    restart: on-failure

  # User microservice 
  ud-user-ms:
    image: user-ms
    container_name: ud-user-ms
    depends_on:
      - ud-rabbitmq
      - ud-postgres
    build:
      context: ./user-ms
      target: debug
    volumes:
      - ./user-ms:/app
      - /app/node_modules
    restart: on-failure

  # User API 
  ud-user:
    image: ud-user
    container_name: ud-user
    depends_on:
      - ud-rabbitmq
    build:
      context: ./user
      target: debug
    volumes:
      - ./user:/app
      - /app/node_modules
    ports: 
      - "3001:3000"
    restart: on-failure

  # Cart microservice 
  ud-cart-ms:
    image: cart-ms
    container_name: ud-cart-ms
    depends_on:
      - ud-rabbitmq
      - ud-postgres
    build:
      context: ./cart-ms
      target: debug
    volumes:
      - ./cart-ms:/app
      - /app/node_modules
    restart: on-failure

  # Cart API 
  ud-cart:
    image: ud-cart
    container_name: ud-cart
    depends_on:
      - ud-rabbitmq
    build:
      context: ./cart
      target: debug
    volumes:
      - ./cart:/app
      - /app/node_modules
    ports: 
      - "3002:3000"

  # Cloth microservice 
  ud-cloth-ms:
    image: cloth-ms
    container_name: ud-cloth-ms
    depends_on:
      - ud-rabbitmq
      - ud-mongodb
    build:
      context: ./cloth-ms
      target: debug
    volumes:
      - ./cloth-ms:/app
      - /app/node_modules
    restart: on-failure

  # Cloth API
  ud-cloth:
    image: ud-cloth
    container_name: ud-cloth
    depends_on:
      - ud-rabbitmq
    build:
      context: ./cloth
      target: debug
    volumes:
      - ./cloth:/app
      - /app/node_modules
    ports: 
      - "3003:3000"
    restart: on-failure

  # Address microservice 
  ud-address-ms:
    image: address-ms
    container_name: ud-address-ms
    depends_on:
      - ud-rabbitmq
      - ud-postgres
    build:
      context: ./address-ms
      target: debug
    volumes:
      - ./address-ms:/app
      - /app/node_modules

  # Address API 
  ud-address:
    image: ud-address
    container_name: ud-address
    depends_on:
      - ud-rabbitmq
    build:
      context: ./address
      target: debug
    volumes:
      - ./address:/app
      - /app/node_modules
    ports: 
      - "3004:3000"
    restart: on-failure

  # Services microservice 
  ud-services-ms:
    image: services-ms
    container_name: ud-services-ms
    depends_on:
      - ud-rabbitmq
      - ud-mongodb
    build:
      context: ./services-ms
      target: debug
    volumes:
      - ./services-ms:/app
      - /app/node_modules
    restart: on-failure

  # Services API
  ud-services:
    image: ud-services
    container_name: ud-services
    depends_on:
      - ud-rabbitmq
    build:
      context: ./services
      target: debug
    volumes:
      - ./services:/app
      - /app/node_modules
    ports: 
      - "3005:3000"
    restart: on-failure

  # Services microservice 
  ud-laundry-ms:
    image: laundry-ms
    container_name: ud-laundry-ms
    depends_on:
      - ud-rabbitmq
      - ud-mongodb
    build:
      context: ./laundry-ms
      target: debug
    volumes:
      - ./laundry-ms:/app
      - /app/node_modules
    restart: on-failure

  # laundry API
  ud-laundry:
    image: ud-laundry
    container_name: ud-laundry
    depends_on:
      - ud-rabbitmq
    build:
      context: ./laundry
      target: debug
    volumes:
      - ./laundry:/app
      - /app/node_modules
    ports: 
      - "3006:3000"
    restart: on-failure