version: '3'

services:
  # RabbitMQ for microservice communication
  ud-rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 15671:15671
      - 5672:5672

  # GateKeeper microservice 
  ud-gatekeeper-ms:
    image: gatekeeper-ms
    container_name: ud-gatekeeper-ms
    depends_on:
      - ud-rabbitmq
    build:
      context: ./gatekeeper-ms
      target: debug
    volumes:
      - ./gatekeeper-ms:/app
    restart: on-failure

  # GateKeeper API 
  ud-gatekeeper:
    image: gatekeeper
    container_name: ud-gatekeeper
    depends_on:
      - ud-rabbitmq
    build:
      context: ./gatekeeper
      target: debug
    volumes:
      - ./gatekeeper:/app
    ports: 
      - 3000:3000
    restart: on-failure