version: '3'

services:

  # Postgres Database
  ud-postgres:
    image: "ud-postgres" # use latest official postgres version
    container_name: ud-postgres
    env_file:
      - ./postgres/database.env # configure postgres
    build:
      context: ./postgres
    ports:
      - "54321:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/ud-postgresql/data/ # persist data even if container shuts down

  # Mongo Database
  ud-mongodb:
    image: "mongo"
    volumes:
      - ./mongodb:/var/mongo/data
    ports:
      - "27017:27017"

  # API Gateway
  # Proxies requests to internal service
  ud-gateway:
    image: ud-gateway
    container_name: ud-gateway
    depends_on: 
      - ud-gatekeeper-ms
      - ud-gatekeeper
      - ud-mongodb
    build:
      context: ./gateway
    volumes: 
      - ./gateway:/var/log/nginx/
    ports: 
      - "80:80"

  # RabbitMQ for microservice communication
  ud-rabbitmq:
    image: rabbitmq:3-management
    container_name: ud-rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"

  # GateKeeper microservice 
  ud-gatekeeper-ms:
    image: gatekeeper-ms
    container_name: ud-gatekeeper-ms
    depends_on:
      - ud-rabbitmq
      - ud-mongodb
    build:
      context: ./gatekeeper-ms
      target: debug
    volumes:
      - ./gatekeeper-ms:/app
      - /app/node_modules
    restart: on-failure

  # GateKeeper API 
  ud-gatekeeper:
    image: ud-gatekeeper
    container_name: ud-gatekeeper
    depends_on:
      - ud-rabbitmq
      - ud-gatekeeper-ms
      - ud-mongodb
    build:
      context: ./gatekeeper
      target: debug
    volumes:
      - ./gatekeeper:/app
      - /app/node_modules
    ports: 
      - "3000:3000"
    restart: on-failure

  # User microservice 
  ud-user-ms:
    image: user-ms
    container_name: ud-user-ms
    depends_on:
      - ud-rabbitmq
      - ud-mongodb
    build:
      context: ./user-ms
      target: debug
    volumes:
      - ./user-ms:/app
      - /app/node_modules
    restart: on-failure

  # User API 
  ud-user:
    image: ud-user
    container_name: ud-user
    depends_on:
      - ud-rabbitmq
      - ud-user-ms
      - ud-mongodb
    build:
      context: ./user
      target: debug
    volumes:
      - ./user:/app
      - /app/node_modules
    ports: 
      - "3001:3000"
    restart: on-failure