version: '3'

services:
  # API Gateway
  # Proxies requests to internal service
  ud-gateway:
    image: ud-gateway
    container_name: ud-gateway
    depends_on: 
      - ud-gatekeeper-ms
      - ud-gatekeeper
    build:
      context: ./gateway
    volumes: 
      - ./gateway:/var/log/nginx/
    ports: 
      - 80:80

  # RabbitMQ for microservice communication
  ud-rabbitmq:
    image: rabbitmq:3-management
    container_name: ud-rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 15671:15671
      - 5672:5672

  # GateKeeper microservice 
  ud-gatekeeper-ms:
    image: gatekeeper-ms
    container_name: ud-gatekeeper-ms
    depends_on:
      - ud-rabbitmq
    build:
      context: ./gatekeeper-ms
      target: debug
    volumes:
      - ./gatekeeper-ms:/app
    restart: on-failure

  # GateKeeper API 
  ud-gatekeeper:
    image: ud-gatekeeper
    container_name: ud-gatekeeper
    depends_on:
      - ud-rabbitmq
      - ud-gatekeeper-ms
    build:
      context: ./gatekeeper
      target: debug
    volumes:
      - ./gatekeeper:/app
    ports: 
      - 3000:3000
    restart: on-failure